{
  "formatVersion": "1.1",
  "component": {
    "group": "net.wurstclient",
    "module": "WurstUI",
    "version": "v7.50.1-MC1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "WurstUI-v7.50.1-MC1.21.8.jar",
          "url": "WurstUI-v7.50.1-MC1.21.8.jar",
          "size": 778247,
          "sha512": "6e2744232a4fd78a4c95f5b62fd02779904e4941a59aadc6da23cb359ef7c99fc2c27a34d27072ab61620c65c2b8dabaf6462fbaa28e81d17804f83f50bbe5c9",
          "sha256": "8944531a86d00598ade874df71abda9a88171f23a2a0f84365e99ace57682b56",
          "sha1": "c17e535c987dc9a1ee057956b0480df3ff373088",
          "md5": "09f5598942fdb833ad4d7e3443763cb4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.4+1.21.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "WurstUI-v7.50.1-MC1.21.8.jar",
          "url": "WurstUI-v7.50.1-MC1.21.8.jar",
          "size": 778247,
          "sha512": "6e2744232a4fd78a4c95f5b62fd02779904e4941a59aadc6da23cb359ef7c99fc2c27a34d27072ab61620c65c2b8dabaf6462fbaa28e81d17804f83f50bbe5c9",
          "sha256": "8944531a86d00598ade874df71abda9a88171f23a2a0f84365e99ace57682b56",
          "sha1": "c17e535c987dc9a1ee057956b0480df3ff373088",
          "md5": "09f5598942fdb833ad4d7e3443763cb4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "WurstUI-v7.50.1-MC1.21.8-sources.jar",
          "url": "WurstUI-v7.50.1-MC1.21.8-sources.jar",
          "size": 542128,
          "sha512": "01c1993190840551a31c803fc29b0a2275f52f695fe26b8ac005b1a3f9a0880666e5fe8bec314d7da0f0883a7d7c711b7a45d61252cddc9281238849488b8bcc",
          "sha256": "0f73770e3fc374cf7e05fd6897c93d7c3038cdf5bbb45ce58b7a9a1ef771e082",
          "sha1": "c78ada80284bfdf2c83fe27da95566c39f9b0016",
          "md5": "5ae5166f576d09050236b93feecec0dd"
        }
      ]
    }
  ]
}
