{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yiyuyan",
    "module": "SuperAccessTransformerPlugin",
    "version": "1.002",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SuperAccessTransformerPlugin-1.002.jar",
          "url": "SuperAccessTransformerPlugin-1.002.jar",
          "size": 9899,
          "sha512": "f3477df303fa5ff2f7f42eb370aa5bb73d5946ccd133d81dfd5144ad95b94897d8dadddda8a0f9fce7abfea7942fca7fe44f31a451eb417af718d981b7264685",
          "sha256": "16e91336ac5c577575caf0967ead7f10044181dbef4a6ddfd245c047767a09bc",
          "sha1": "5c0399cbe1aa295704feed0462a4fb2530ee7552",
          "md5": "455e61626272cfa5f6c27214ce6d31c4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "SuperAccessTransformerPlugin-1.002.jar",
          "url": "SuperAccessTransformerPlugin-1.002.jar",
          "size": 9899,
          "sha512": "f3477df303fa5ff2f7f42eb370aa5bb73d5946ccd133d81dfd5144ad95b94897d8dadddda8a0f9fce7abfea7942fca7fe44f31a451eb417af718d981b7264685",
          "sha256": "16e91336ac5c577575caf0967ead7f10044181dbef4a6ddfd245c047767a09bc",
          "sha1": "5c0399cbe1aa295704feed0462a4fb2530ee7552",
          "md5": "455e61626272cfa5f6c27214ce6d31c4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "SuperAccessTransformerPlugin-1.002-sources.jar",
          "url": "SuperAccessTransformerPlugin-1.002-sources.jar",
          "size": 3730,
          "sha512": "4460f343e2e64d574dfc6d51baf6ecec9628d65e99da14f650adaf654a3e0ffb0f85c0e70b7f84987ca06e89cb62e7ca8818dd54edacb999d8e334b38ee98b38",
          "sha256": "02e61f8b81a6f9899289828f823914c01a4667556db3cffb04c4a67ecf0b9c7f",
          "sha1": "4870e215464781cad099b31678239840b35ebfc2",
          "md5": "bb0180c01d6c6aaabe3a83cd0ccedc52"
        }
      ]
    }
  ]
}
