{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.yiyuyan",
    "module": "SuperAccessTransformerPlugin",
    "version": "1.002",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "SuperAccessTransformerPlugin-1.002.jar",
          "url": "SuperAccessTransformerPlugin-1.002.jar",
          "size": 10184,
          "sha512": "fc26af425d5fd2d20fe6b6d3c58fd58c28fbfb5f75e73568e4121b4d908260ceff63301d0542ddd91c14e439b08caf736f411a2de892c64c6f916ad1722b4a0d",
          "sha256": "90d90c9798eb10f410ae6817a681f97676d382b47140ddf205ffa1ebbc61ea38",
          "sha1": "90033164383e463425586b2ada9c637c81357933",
          "md5": "1b06588d34c809d15d1e5459ca38ef13"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.6"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.6"
          }
        }
      ],
      "files": [
        {
          "name": "SuperAccessTransformerPlugin-1.002.jar",
          "url": "SuperAccessTransformerPlugin-1.002.jar",
          "size": 10184,
          "sha512": "fc26af425d5fd2d20fe6b6d3c58fd58c28fbfb5f75e73568e4121b4d908260ceff63301d0542ddd91c14e439b08caf736f411a2de892c64c6f916ad1722b4a0d",
          "sha256": "90d90c9798eb10f410ae6817a681f97676d382b47140ddf205ffa1ebbc61ea38",
          "sha1": "90033164383e463425586b2ada9c637c81357933",
          "md5": "1b06588d34c809d15d1e5459ca38ef13"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "SuperAccessTransformerPlugin-1.002-sources.jar",
          "url": "SuperAccessTransformerPlugin-1.002-sources.jar",
          "size": 3841,
          "sha512": "6301164cd8aaef1ccafc5f0292adbd6e279435fdf760da3774613cf3344dd0943a1ad5a9a8a612cb9abeed20f6b237fa9464bc7ddae61bf7cba15ee9ff227bda",
          "sha256": "453fbf799a79da5b17f0a2967d7992f5e201e6521eb9b499e54170381bbaa706",
          "sha1": "df42c82fc16ac9ac79191f7a39820e71c77fa231",
          "md5": "5a7864b4f6537551bff33ab28e41b431"
        }
      ]
    }
  ]
}
