{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.17-cm.local",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-cm.local.jar",
          "url": "fabric-loom-1.17-cm.local.jar",
          "size": 1438517,
          "sha512": "094070ce401ef6d8b5976a375713fc8cb38bb6ae8c6542b4fde13e3814a377686d5c74ffa09d917daeb85d554a0ca3145e034bd2bc2ae2162ebb979e129fce20",
          "sha256": "e3fe123757a1a5940d95825e7e1e67acd08538d098f5a5d42be4c57d77d4110e",
          "sha1": "5a7d13a72a7366b11991a369a750205cfb75ece1",
          "md5": "db5830787726c99ca2c3eb7c82cb7b06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "9.5.0",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.14.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.10.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            },
            {
              "group": "*",
              "module": "guava"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.14.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "class-tweaker",
          "version": {
            "requires": "0.3.0-beta.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.3"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercurymixin",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.3.20"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.17-cm.local.jar",
          "url": "fabric-loom-1.17-cm.local.jar",
          "size": 1438517,
          "sha512": "094070ce401ef6d8b5976a375713fc8cb38bb6ae8c6542b4fde13e3814a377686d5c74ffa09d917daeb85d554a0ca3145e034bd2bc2ae2162ebb979e129fce20",
          "sha256": "e3fe123757a1a5940d95825e7e1e67acd08538d098f5a5d42be4c57d77d4110e",
          "sha1": "5a7d13a72a7366b11991a369a750205cfb75ece1",
          "md5": "db5830787726c99ca2c3eb7c82cb7b06"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.17-cm.local-sources.jar",
          "url": "fabric-loom-1.17-cm.local-sources.jar",
          "size": 857140,
          "sha512": "dc28a17767887b8b380934e0b5ccf6e72293e2b32ab97f0ed6e5767fb82dad7300ea7b9f1e33ef6905cd3e65716ce02a8825ed8b84fd975ccd500ae7af7214b4",
          "sha256": "588a7888d81563da454bd07381b2f3f624d6fe49a94e46cb39f130c00d261ec6",
          "sha1": "0043cf3764fb8de5cc05fc80d55231276f96b78f",
          "md5": "8f7179c6a4ba50d8ca330f7a49a6763f"
        }
      ]
    }
  ]
}
