{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.ksmcbrigade",
    "module": "cser-common-1.21",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "cser-common-1.21-1.0.jar",
          "url": "cser-common-1.21-1.0.jar",
          "size": 12318,
          "sha512": "af15c30731d13d5a64c69121ec3823b6f57f4b661bc2838a3be96a5331fcbb46401af1b17ed272256f27d1aec9832ea5cce0e364975f6bcb9471257686897f56",
          "sha256": "8d3ed90180bdddc06745d38d566affb54be11a18867589b20a5ef9caa9c3541c",
          "sha1": "0fe55a0aa89d276dd6813e6a13b5097a480c0147",
          "md5": "edc1684abe13ddb71db5dcce030d1308"
        }
      ],
      "capabilities": [
        {
          "group": "cn.ksmcbrigade",
          "name": "cser",
          "version": "1.0"
        },
        {
          "group": "cn.ksmcbrigade",
          "name": "cser-common-1.21",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cser-common-1.21-1.0.jar",
          "url": "cser-common-1.21-1.0.jar",
          "size": 12318,
          "sha512": "af15c30731d13d5a64c69121ec3823b6f57f4b661bc2838a3be96a5331fcbb46401af1b17ed272256f27d1aec9832ea5cce0e364975f6bcb9471257686897f56",
          "sha256": "8d3ed90180bdddc06745d38d566affb54be11a18867589b20a5ef9caa9c3541c",
          "sha1": "0fe55a0aa89d276dd6813e6a13b5097a480c0147",
          "md5": "edc1684abe13ddb71db5dcce030d1308"
        }
      ],
      "capabilities": [
        {
          "group": "cn.ksmcbrigade",
          "name": "cser",
          "version": "1.0"
        },
        {
          "group": "cn.ksmcbrigade",
          "name": "cser-common-1.21",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cser-common-1.21-1.0-sources.jar",
          "url": "cser-common-1.21-1.0-sources.jar",
          "size": 8875,
          "sha512": "730fb9cf655dd1db41e08f9d33f2504112c200b74984149ba645c545ee3215486f6e897d764fa69b790fe566d77f430fd87832460631fa55092073fdfd47de4b",
          "sha256": "36c0505c7a817fe9f1836f6adb0eb2e4bd03887ec0a3907adcb533620b7fa431",
          "sha1": "98cdd60abd264b3810ea43820ba19f2e48175884",
          "md5": "f3dc32a569abcf9838414cf89fc04c00"
        }
      ],
      "capabilities": [
        {
          "group": "cn.ksmcbrigade",
          "name": "cser",
          "version": "1.0"
        },
        {
          "group": "cn.ksmcbrigade",
          "name": "cser-common-1.21",
          "version": "1.0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cser-common-1.21-1.0-javadoc.jar",
          "url": "cser-common-1.21-1.0-javadoc.jar",
          "size": 133564,
          "sha512": "b611a475df9ea58ae1fbd1631774e39c73c6e4eb7a9eab868ca544d389797b95b144baef7c12f9330dbe6ab4c5469fc42a420ed77b6dd4adafe6c792ef6347a1",
          "sha256": "f268e520cd60d7b71ed0ffcc9e79c8cf520ed6423de49921ce3d65838ec78a3d",
          "sha1": "3a513856622b73cd2fc7d2e4227fac4fa1138f6f",
          "md5": "823c4ab00cca71e5aadf5c25eb68fcb1"
        }
      ],
      "capabilities": [
        {
          "group": "cn.ksmcbrigade",
          "name": "cser",
          "version": "1.0"
        },
        {
          "group": "cn.ksmcbrigade",
          "name": "cser-common-1.21",
          "version": "1.0"
        }
      ]
    }
  ]
}
