{
  "formatVersion": "1.1",
  "component": {
    "group": "net.wurstclient",
    "module": "WurstUI",
    "version": "v7.50.1-p-MC1.21.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "WurstUI-v7.50.1-p-MC1.21.8.jar",
          "url": "WurstUI-v7.50.1-p-MC1.21.8.jar",
          "size": 778258,
          "sha512": "aa4f805c066789a5a7f193eecdd3734b0ee5532ca368f205317dc8077fc72efcb4c8e218bfb329d2d49a1fd89a89a8371293babf07dcd1784940a1dbe7458179",
          "sha256": "5471d2cb0ca9be49cf12ec2147e13ee70d8b9bb46ead2cac88717f33d76868a2",
          "sha1": "a714a98608b25adb2dfa460bf30f3d17fef807a7",
          "md5": "44681f72a021187f0c5d4534c18c650c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.17.2"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.133.4+1.21.8"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "WurstUI-v7.50.1-p-MC1.21.8.jar",
          "url": "WurstUI-v7.50.1-p-MC1.21.8.jar",
          "size": 778258,
          "sha512": "aa4f805c066789a5a7f193eecdd3734b0ee5532ca368f205317dc8077fc72efcb4c8e218bfb329d2d49a1fd89a89a8371293babf07dcd1784940a1dbe7458179",
          "sha256": "5471d2cb0ca9be49cf12ec2147e13ee70d8b9bb46ead2cac88717f33d76868a2",
          "sha1": "a714a98608b25adb2dfa460bf30f3d17fef807a7",
          "md5": "44681f72a021187f0c5d4534c18c650c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "WurstUI-v7.50.1-p-MC1.21.8-sources.jar",
          "url": "WurstUI-v7.50.1-p-MC1.21.8-sources.jar",
          "size": 540794,
          "sha512": "217325aa6be66c7c5039364818a81a505ec97cbbbc24b0e2be1147c80f044e3a54f21c19b5231dc68b5f196337c5dfcf59d938ee5e09f1c15ea903670d9ae20d",
          "sha256": "e0bb380cbcb92eacc300be99409d815b753496c0c7ca73d4609387b66bd864f7",
          "sha1": "bf679449e9386a89e8a1a07d76621bd0648e1360",
          "md5": "6191bb06ede9aa9428aa503e08db5679"
        }
      ]
    }
  ]
}
