{
  "formatVersion": "1.1",
  "component": {
    "group": "cn.ksmcbrigade",
    "module": "npop",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "npop-1.1.jar",
          "url": "npop-1.1.jar",
          "size": 8521,
          "sha512": "c238a7a62aa5cb090af85dd5d8646b95ec48e2854daad059e304c3772d7f84818123e1332285b7dd40305ce8da75085ddc98ad5ef4f16e323f86afa434fe03a8",
          "sha256": "9a483176341db4a72276c04d1c6a44493b1ba35621829cd4688f53dce49b70b9",
          "sha1": "978815587a50d1598f607803da643a581089acaf",
          "md5": "49a5a34caaa02e093621090c7451ec39"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.6_mapped_official_1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "npop-1.1.jar",
          "url": "npop-1.1.jar",
          "size": 8521,
          "sha512": "c238a7a62aa5cb090af85dd5d8646b95ec48e2854daad059e304c3772d7f84818123e1332285b7dd40305ce8da75085ddc98ad5ef4f16e323f86afa434fe03a8",
          "sha256": "9a483176341db4a72276c04d1c6a44493b1ba35621829cd4688f53dce49b70b9",
          "sha1": "978815587a50d1598f607803da643a581089acaf",
          "md5": "49a5a34caaa02e093621090c7451ec39"
        }
      ]
    }
  ]
}
